# Generated by Django 4.1.2 on 2022-10-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ID',
            new_name='id',
        ),
    ]
